---
  - name: installing and launch metricbeat
    hosts: webservers
    become: yes
    tasks:
    - name: stop metricbeat
      command: service metricbeat stop

      # Use command module
    - name: download metricbeat .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      # Use command module
    - name: Install metricbeat .deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

      # Use copy module
    - name: Drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

      # Use command module
    - name: enable and configure system module
      command: metricbeat modules enable docker

      # Use command module
    - name: setup metricbeat
      command: metricbeat setup

      # Use command module
    - name: Start metricbeat service
      command: metricbeat -e
